<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Auth\Module'                       => __DIR__ . '/Module.php',
    'Auth\Controller\AuthController'    => __DIR__ . '/src/Auth/Controller/AuthController.php',
    'Auth\Controller\SuccessController' => __DIR__ . '/src/Auth/Controller/SuccessController.php',
    'Auth\Model\MyAuthStorage'          => __DIR__ . '/src/Auth/Model/MyAuthStorage.php',
    'Auth\Model\User'                   => __DIR__ . '/src/Auth/Model/User.php',
);